apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ceph-metrics
    namespace: metrics
    labels:
      app: ceph-metrics
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      app: ceph-metrics
      deploymentconfig: ceph-metrics
    template:
      metadata:
        labels:
          app: ceph-metrics
          deploymentconfig: ceph-metrics
      spec:
        volumes:
          - name: ceph-clusters
            secret:
              secretName: ceph-clusters
        containers:
          - name: ceph-metrics
            image: buhrietoe/ceph-metrics
            env:
              - name: INFLUXDB_HOST
                value: influxdb-relay
            volumeMounts:
              - name: ceph-clusters
                mountPath: /etc/ceph/clusters
            resources: {}
        restartPolicy: Always
        securityContext: {}
