- set_fact:
    openshift_project: "{{ item }}"

- name: create openshift project
  command: >
    {{ openshift_admin_binary }} new-project {{ openshift_project.name }}
  register: project_task
  failed_when: false
  changed_when: "not project_task.stdout.find('already exists')"

- name: setup openshift projects policies
  command: >
    {{ openshift_admin_binary }} -n {{ openshift_project.name }} policy {{ item }}
  with_items: "{{ openshift_project.policies }}"
  register: permissions_task
  failed_when: "permissions_task.rc != 0"
  changed_when: false
