apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: kube-source
    namespace: internal
    labels:
      app: kube-source

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: kube-source
    namespace: internal
    labels:
      app: kube-source
  spec:
    triggers:
      -
        type: ConfigChange
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: 'https://github.com/allen13/kube-source'
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: 'kube-source:latest'
    resources:
    postCommit:

- apiVersion: v1
  kind: Service
  metadata:
    name: kube-source
    namespace: internal
    labels:
      app: kube-source
  spec:
    ports:
      -
        name: 5606-tcp
        protocol: TCP
        port: 5606
        targetPort: 5606
    selector:
      app: kube-source
    portalIP: {{ kube_source_service_ip }}
    clusterIP: {{ kube_source_service_ip }}
    type: ClusterIP
    sessionAffinity: None

- apiVersion: v1
  kind: Route
  metadata:
    name: kube-source
    namespace: internal
    labels:
      app: kube-source
  spec:
    to:
      kind: Service
      name: kube-source
      weight: 100
    port:
      targetPort: 5606-tcp
    tls:
      termination: passthrough

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: kube-source
    namespace: internal
    labels:
      app: kube-source
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources:
    triggers:
      -
        type: ConfigChange
      -
        type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - kube-source
          from:
            kind: ImageStreamTag
            namespace: internal
            name: 'kube-source:latest'
    replicas: 1
    test: false
    selector:
      app: kube-source
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: kube-source
      spec:
        volumes:
          -
            name: kube-source-certs
            secret:
              secretName: kube-source-certs
        containers:
          -
            name: kube-source
            image: '192.168.0.121:5000/internal/kube-source:latest'
            ports:
              -
                containerPort: 5606
                protocol: TCP
            env:
              -
                name: KUBE_SOURCE_CONTAINER_IP
                value: 169.46.3.229
              -
                name: KUBE_SOURCE_TLS_ENABLED
                value: 'true'
              -
                name: KUBE_SOURCE_TLS_CERT
                value: /etc/kube-source/ssl/kube-source.crt
              -
                name: KUBE_SOURCE_TLS_KEY
                value: /etc/kube-source/ssl/kube-source.key
            resources:
            volumeMounts:
              -
                name: kube-source-certs
                mountPath: /etc/kube-source/ssl/
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
