- name: htpasswd-provider
  challenge: true
  login: true
  mappingMethod: claim
  provider:
    apiVersion: v1
    kind: HTPasswdPasswordIdentityProvider
    file: {{ openshift_master_config_path }}/users.htpasswd
