admissionConfig:
  pluginConfig: null
apiLevels:
- v1
apiVersion: v1
assetConfig:
  extensionDevelopment: false
  extensionScripts: null
  extensionStylesheets: null
  extensions: null
  loggingPublicURL: ""
  logoutURL: ""
  masterPublicURL: {{ openshift_master_public_url }}
  metricsPublicURL: {{ openshift_metrics_public_url }}
  publicURL: {{ openshift_master_public_url }}/console/
  servingInfo:
    bindAddress: 0.0.0.0:8443
    bindNetwork: tcp4
    certFile: master.server.crt
    clientCA: ""
    keyFile: master.server.key
    maxRequestsInFlight: 0
    namedCertificates: null
    requestTimeoutSeconds: 3600
controllerLeaseTTL: 30
controllers: '*'
corsAllowedOrigins:
- openshift.service.os
- {{ private_ip }}:8443
- 127.0.0.1
- localhost
disabledFeatures: null
dnsConfig:
  allowRecursiveQueries: true
  bindAddress: {{ private_ip }}:5353
  bindNetwork: tcp4
etcdClientInfo:
  ca: ""
  certFile: ""
  keyFile: ""
  urls:
  - http://127.0.0.1:2379
etcdConfig: null
etcdStorageConfig:
  kubernetesStoragePrefix: kubernetes.io
  kubernetesStorageVersion: v1
  openShiftStoragePrefix: openshift.io
  openShiftStorageVersion: v1
imageConfig:
  format: openshift/origin-${component}:${version}
  latest: false
imagePolicyConfig:
  disableScheduledImport: false
  maxImagesBulkImportedPerRepository: 5
  maxScheduledImageImportsPerMinute: 60
  scheduledImageImportMinimumIntervalSeconds: 900
kind: MasterConfig
kubeletClientInfo:
  ca: ca.crt
  certFile: master.kubelet-client.crt
  keyFile: master.kubelet-client.key
  port: 10250
kubernetesMasterConfig:
  admissionConfig:
    pluginConfig: null
  apiLevels: null
  apiServerArguments: null
  disabledAPIGroupVersions: {}
  masterCount: {{ groups['openshift-master']|length }}
  masterIP: {{ private_ip }}
  podEvictionTimeout: 5m
  proxyClientInfo:
    certFile: master.proxy-client.crt
    keyFile: master.proxy-client.key
  schedulerConfigFile: ""
  servicesNodePortRange: 30000-32767
  servicesSubnet: {{ openshift_service_subnet }}
  staticNodeNames: null
masterClients:
  externalKubernetesKubeConfig: ""
  openshiftLoopbackKubeConfig: openshift-master.kubeconfig
masterPublicURL: {{ openshift_master_public_url }}
networkConfig:
  clusterNetworkCIDR: {{ openshift_cluster_subnet }}
  hostSubnetLength: {{ openshift_cluster_subnet_length }}
  networkPluginName: {{ openshift_network_plugin }}
  serviceNetworkCIDR: {{ openshift_service_subnet }}
  #this enables external service ips
  externalIPNetworkCIDRs:
  - 0.0.0.0/0
oauthConfig:
  alwaysShowProviderSelection: false
  assetPublicURL: {{ openshift_master_public_url }}/console/
  grantConfig:
    method: auto
  identityProviders:
{% for line in openshift_identity_providers_yamlized.splitlines() %}
  {{ line }}
{% endfor %}
  masterCA: ca.crt
  masterPublicURL: {{ openshift_master_public_url }}
  masterURL: {{ openshift_master_api_url }}
  sessionConfig:
    sessionMaxAgeSeconds: 300
    sessionName: ssn
    sessionSecretsFile: ""
  templates: null
  tokenConfig:
    accessTokenMaxAgeSeconds: 604800
    authorizeTokenMaxAgeSeconds: 300
pauseControllers: false
policyConfig:
  bootstrapPolicyFile: policy.json
  openshiftInfrastructureNamespace: openshift-infra
  openshiftSharedResourcesNamespace: openshift
projectConfig:
  defaultNodeSelector: "dc={{ openshift_primary_dc }}"
  projectRequestMessage: ""
  projectRequestTemplate: ""
  securityAllocator:
    mcsAllocatorRange: s0:/2
    mcsLabelsPerProject: 5
    uidAllocatorRange: 1000000000-1999999999/10000
routingConfig:
  subdomain: apps.{{ openshift_external_dns_domain }}
serviceAccountConfig:
  limitSecretReferences: false
  managedNames:
  - default
  - builder
  - deployer
  masterCA: ca.crt
  privateKeyFile: serviceaccounts.private.key
  publicKeyFiles:
  - serviceaccounts.public.key
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: master.server.crt
  clientCA: ca.crt
  keyFile: master.server.key
  maxRequestsInFlight: 0
  namedCertificates: null
  requestTimeoutSeconds: 3600
