apiVersion: v1
kind: List
metadata:
  name: metrics-deployer-setup
  annotations:
    description: "Required dependencies for the metrics deployer pod."
    tags: "infrastructure"
labels:
  metrics-infra: deployer
  provider: openshift
  component: deployer
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: metrics-deployer
    secrets:
      - name: metrics-deployer
