apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: golerta
    namespace: metrics
    labels:
      app: golerta
  spec:
    ports:
      - name: 5608-tcp
        protocol: TCP
        port: 5608
        targetPort: 5608
    selector:
      app: golerta
    portalIP: {{ golerta_service_ip }}
    clusterIP: {{ golerta_service_ip }}
    type: ClusterIP
    externalIPs:
{% for line in golerta_service_external_ips %}
      - {{ line }}
{% endfor %}

- apiVersion: v1
  kind: Route
  metadata:
    name: golerta
    namespace: metrics
    labels:
      app: golerta
  spec:
    to:
      kind: Service
      name: golerta
    port:
      targetPort: 5608-tcp
    tls:
      termination: passthrough

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: golerta
    namespace: metrics
    labels:
      app: golerta
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {  }
    triggers:
      -
        type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: golerta
    template:
      metadata:
        labels:
          app: golerta
      spec:
        volumes:
          -
            name: golerta-certs
            secret:
              secretName: golerta-certs
        containers:
          -
            name: golerta
            image: allen13/golerta
            ports:
              -
                containerPort: 5608
                protocol: TCP
            env:
              -
                name: RETHINKDB_ADDRESS
                value: golerta-rethinkdb:28015
              -
                name: SIGNING_KEY
                value: {{ golerta_signing_key }}
              -
                name: TLS_ENABLED
                value: 'true'
              -
                name: TLS_CERT
                value: /etc/golerta/ssl/golerta.crt
              -
                name: TLS_KEY
                value: /etc/golerta/ssl/golerta.key
            resources: {  }
            volumeMounts:
              -
                name: golerta-certs
                mountPath: /etc/golerta/ssl/
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {  }

- apiVersion: v1
  kind: Service
  metadata:
    name: golerta-rethinkdb
    namespace: metrics
    labels:
      app: golerta-rethinkdb
  spec:
    ports:
      -
        name: 8080-tcp
        protocol: TCP
        port: 8080
        targetPort: 8080
      -
        name: 28015-tcp
        protocol: TCP
        port: 28015
        targetPort: 28015
      -
        name: 29015-tcp
        protocol: TCP
        port: 29015
        targetPort: 29015
    selector:
      app: golerta-rethinkdb
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {  }

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: golerta-rethinkdb
    namespace: metrics
    labels:
      app: golerta-rethinkdb
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {  }
    triggers:
      -
        type: ConfigChange
    replicas: 1
    test: false
    selector:
      app: golerta-rethinkdb
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: golerta-rethinkdb
          deploymentconfig: golerta-rethinkdb
      spec:
        volumes:
          -
            name: golerta-rethinkdb-data
            emptyDir: {  }
        containers:
          -
            name: golerta-rethinkdb
            image: rethinkdb:2
            ports:
              -
                containerPort: 8080
                protocol: TCP
              -
                containerPort: 28015
                protocol: TCP
              -
                containerPort: 29015
                protocol: TCP
            resources: {  }
            volumeMounts:
              -
                name: golerta-rethinkdb-data
                mountPath: /data
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
