apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: Service
  metadata:
    name: kapacitor
    namespace: metrics
    labels:
      app: kapacitor
  spec:
    ports:
      - name: 9092-tcp
        protocol: TCP
        port: 9092
        targetPort: 9092
    selector:
      app: kapacitor
    portalIP: {{ kapacitor_service_ip }}
    clusterIP: {{ kapacitor_service_ip }}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: kapacitor
    namespace: metrics
    labels:
      app: kapacitor
  spec:
    strategy:
      type: Recreate
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      app: kapacitor
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: kapacitor
      spec:
        volumes:
          - name: kapacitor-data
{% for line in kapacitor_volume_yamlized.splitlines() %}
            {{ line }}
{% endfor %}
        containers:
          - name: kapacitor
            image: allen13/kapacitor:latest
            ports:
              - containerPort: 9092
                protocol: TCP
            env:
              - name: INFLUXDB_SUBSCRIPTION_DB_RP
                value: {{ influxdb_default_retention_policy }}
              - name: ALERTA_API_URL
                value: https://golerta:5608
              - name: ALERTA_TOKEN
                value: {{ golerta_agent_token }}
            imagePullPolicy: Always
            volumeMounts:
              - name: kapacitor-data
                mountPath: /var/lib/kapacitor
        restartPolicy: Always
        dnsPolicy: ClusterFirst
        nodeSelector:
          dc: {{ openshift_dc }}
