apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: surface
  spec:
    ports:
      - name: web
        port: 8000
        protocol: TCP
    selector:
      name: surface
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: surface
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: surface-build
    name: surface-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: surface:latest
    resources: {}
    source:
      git:
        uri: https://github.com/allen13/openshift-example.git
      type: Git
    strategy:
      type: Docker
    triggers:
      - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: surface
  spec:
    replicas: 2
    selector:
      name: surface
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 120
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: surface
      spec:
        containers:
        - name: surface
          image: surface
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8000
            protocol: TCP
          resources: {}
        restartPolicy: Always
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - surface
          from:
            kind: ImageStreamTag
            name: surface:latest
      - type: ConfigChange
  status: {}
kind: List
metadata: {}
